/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompagniesRouteImport } from './routes/compagnies'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HorairesRouteImport } from './routes/horaires'
import { Route as LignesRouteImport } from './routes/lignes'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as LignesSlugRouteImport } from './routes/lignes.$slug'
import { Route as PortsSlugRouteImport } from './routes/ports.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompagniesRoute = CompagniesRouteImport.update({
  id: '/compagnies',
  path: '/compagnies',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HorairesRoute = HorairesRouteImport.update({
  id: '/horaires',
  path: '/horaires',
  getParentRoute: () => rootRouteImport,
} as any)
const LignesRoute = LignesRouteImport.update({
  id: '/lignes',
  path: '/lignes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const LignesSlugRoute = LignesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LignesRoute,
} as any)
const PortsSlugRoute = PortsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compagnies': typeof CompagniesRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/horaires': typeof HorairesRoute
  '/lignes': typeof LignesRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/ports': typeof PortsRouteWithChildren
  '/lignes/$slug': typeof LignesSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compagnies': typeof CompagniesRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/horaires': typeof HorairesRoute
  '/lignes': typeof LignesRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/ports': typeof PortsRouteWithChildren
  '/lignes/$slug': typeof LignesSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compagnies': typeof CompagniesRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/horaires': typeof HorairesRoute
  '/lignes': typeof LignesRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/ports': typeof PortsRouteWithChildren
  '/lignes/$slug': typeof LignesSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/compagnies'
    | '/compte'
    | '/confidentialite'
    | '/contact'
    | '/guide'
    | '/horaires'
    | '/lignes'
    | '/mentions-legales'
    | '/ports'
    | '/lignes/$slug'
    | '/ports/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/compagnies'
    | '/compte'
    | '/confidentialite'
    | '/contact'
    | '/guide'
    | '/horaires'
    | '/lignes'
    | '/mentions-legales'
    | '/ports'
    | '/lignes/$slug'
    | '/ports/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/compagnies'
    | '/compte'
    | '/confidentialite'
    | '/contact'
    | '/guide'
    | '/horaires'
    | '/lignes'
    | '/mentions-legales'
    | '/ports'
    | '/lignes/$slug'
    | '/ports/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CompagniesRoute: typeof CompagniesRoute
  CompteRoute: typeof CompteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  GuideRoute: typeof GuideRoute
  HorairesRoute: typeof HorairesRoute
  LignesRoute: typeof LignesRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PortsRoute: typeof PortsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compagnies': {
      id: '/compagnies'
      path: '/compagnies'
      fullPath: '/compagnies'
      preLoaderRoute: typeof CompagniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horaires': {
      id: '/horaires'
      path: '/horaires'
      fullPath: '/horaires'
      preLoaderRoute: typeof HorairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lignes': {
      id: '/lignes'
      path: '/lignes'
      fullPath: '/lignes'
      preLoaderRoute: typeof LignesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lignes/$slug': {
      id: '/lignes/$slug'
      path: '/$slug'
      fullPath: '/lignes/$slug'
      preLoaderRoute: typeof LignesSlugRouteImport
      parentRoute: typeof LignesRoute
    }
    '/ports/$slug': {
      id: '/ports/$slug'
      path: '/$slug'
      fullPath: '/ports/$slug'
      preLoaderRoute: typeof PortsSlugRouteImport
      parentRoute: typeof PortsRoute
    }
  }
}

interface LignesRouteChildren {
  LignesSlugRoute: typeof LignesSlugRoute
}

const LignesRouteChildren: LignesRouteChildren = {
  LignesSlugRoute: LignesSlugRoute,
}

const LignesRouteWithChildren =
  LignesRoute._addFileChildren(LignesRouteChildren)

interface PortsRouteChildren {
  PortsSlugRoute: typeof PortsSlugRoute
}

const PortsRouteChildren: PortsRouteChildren = {
  PortsSlugRoute: PortsSlugRoute,
}

const PortsRouteWithChildren = PortsRoute._addFileChildren(PortsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CompagniesRoute: CompagniesRoute,
  CompteRoute: CompteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  GuideRoute: GuideRoute,
  HorairesRoute: HorairesRoute,
  LignesRoute: LignesRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PortsRoute: PortsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
